### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by ernesto-jimenez**
Enabling travis on the project.

I tried the configuration on my fork and it worked:
https://travis-ci.org/ernesto-jimenez/gallium/builds/163285132

### CODE REVIEW

**Comment by alexflint** [comment]
Oh, this is great.

**Comment by alexflint** [comment]
(I'll set up travis at the other end and add a badge in another pr)

**Comment by joeblew99** [comment]
if this building on linux machine ?

**Comment by ernesto-jimenez** [comment]
@joeblew99 it is currently setup to run the tests on OS X, since it is what is currently supported.

Linux OS can be added to the file in the PR adding support for Linux.

**Comment by joeblew99** [comment]
ok. was just curious

eager to get windows cranking :)

**Pull request merged**
