### PR TITLE
Implement server sent events

### PR DESCRIPTION
**Pull request by ernesto-jimenez**
This pull request builds on top of PR #20

Implements Server Sent Events in our custom HTTP server. Allowing the Go app to
issue events that will be sent to all the app windows subscribed to the events.

Emitting an event:

``` go
app.Emit("menu", "test")
```

Subscribing to events:

``` html
<p>Events:</p>
<ul id="events"></ul>
<script type="text/javascript">
function append(txt) {
  var ul = document.getElementById("events");
  var li = document.createElement('li');
  li.innerHTML = txt;
  ul.appendChild(li);
}

append("connecting");

var source = new EventSource("/gallium.events");

source.onopen = function () { append("connected"); };
source.onerror = function () { append("connection failed"); };

source.addEventListener("menu", function (event) {
  append("Clicked: "+event.data);
});
</script>
```

### CODE REVIEW

**Comment by ernesto-jimenez** [comment]
The PR includes a working `events` example.

**Comment by joeblew99** [comment]
nice. I can use this for the types of things i build. I am very into CQRS and Redux patterns.
thanks for this..

**Comment by joeblew99** [comment]
Looks like a decent way to do it.
Seem to em that this envisaged to only be used for infrastructure level events, like telling windows that to do. For business level events (liek telling a contacts list that a new contact was added) developers shoudl use a completely different mechanism as per their own architecture.

Curious if i got this right ?

**Comment by avelino** [comment]
This project dead?

**Pull request closed without merging**
