### PR TITLE
various bits...

### PR DESCRIPTION
**Pull request by joeblew99**
Cleaned up up examples, with build script and git ignore so its easy for others.

Added docs for cross platform package needed. Just initial ideas.
- We can test these cross platform libraries first (on actual windows, osx and linux) before writing too much gallium core code to depend on them.
- These can then be integrated to work with the cross platform gallium core over time. We can converge then.

Fixed a spelling error.

### CODE REVIEW

**Comment by alexflint** [comment]
Hey @joeblew99, this is awesome!

That list of packages is super useful - thanks for taking the time to write it up. I think you're right that the wiki is probably the best place for it. I didn't realize that editing the wiki was restricted - have fixed that now, so you should be able to edit it. Can you move that over to the wiki?

Nice wsrpc example. My main request in order to merge it in would be to make it a bit more minimal - it's always nice with the examples to be able to do run them with a fresh git clone without needing to `go get` anything else (and also without introducing any extra dependencies into `gallium` itself). 

One option would be to have a minimal version of `wsrpc` in the gallium examples directory, plus a pointer to a full version in a separate repo. The one in the examples directory could be all in a single package, have just plain .js files rather than `gopherjs`, etc, while the one in a separate repo could be more full-featured.

What do you think?

**Comment by joeblew99** [comment]
Hey @alexflint . glad you are open to this.

1. Yes i will move the suggested packages to the wiki

2. Regarding wsrpc dependencies...
Its allot of work to split it out. 
What if i just change the t-build.sh script to ensure it pulls all needing things in. Its not much:
- github.com/gopherjs/gopherjs
- github.com/gopherjs/jquery
- github.com/gopherjs/websocket
- golang.org/x/net/websocket

go-bindata is already an external, but i can add this to build script.
Also i was thinking of changing it out to use this: https://github.com/shurcooL/vfsgen

**Comment by alexflint** [comment]
Hey @joeblew99, thanks for making the wiki page - I was just checking out some of those packages and I particularly like `systray`. It's kind of interesting, though I guess not completely surprising that gallium independently uses the exact same `onReady` API as them.

The main reason for making the example a bit more minimal is really so that users can look at it and quickly understand something new about how to use gallium, without needing to spend very much time to understand the example itself. I think the gold standard for examples is a single package in a single source file, and only as much code as will fit on a single screen. That's not always achievable (e.g. sometimes you need html/js files, which just can't be in the same file, etc) but I think we should try to get as close as possible.

I totally understand that it's quite a bit of work to reduce the amount of code. One other option would be to have a "list of projects that use gallium", and have wsrpc in a separate repo. That would also free you up to make changes whenever you need to. Let me know what you think.

**Comment by joeblew99** [comment]
hey @alexflint 

I pulled out lots of complexity. I agree with you it was too much for a demo.
Now its showing a simple and effective way of bundling resources with a backend an live templating.

The go gets are there. Any examples to work some salt are gonna need to use some go gettable resources i feel. :) 

have a looksy. Happy to pull it all out if you really dont want it. Not attached :)

**Pull request closed without merging**
